--
-- Script was generated by Devart dbForge Studio for MySQL, Version 7.2.58.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 17/05/2018 10:09:18 p. m.
-- Server version: 5.5.5-10.1.21-MariaDB
-- Client version: 4.1
--


DROP DATABASE IF EXISTS db_challenge;
CREATE DATABASE db_challenge
	CHARACTER SET utf8mb4
	COLLATE utf8mb4_unicode_ci;

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

USE db_challenge;

CREATE TABLE profiles (
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  rfc VARCHAR(18) DEFAULT NULL,
  principal_name VARCHAR(50) DEFAULT NULL,
  business_name VARCHAR(80) DEFAULT NULL,
  phone VARCHAR(10) NOT NULL,
  email VARCHAR(80) NOT NULL,
  created_at TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
AVG_ROW_LENGTH = 16384
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

INSERT INTO profiles VALUES
(1, 'CASF930418QH8', 'José Francisco Carrera Sánchez', 'Villasoft S.A. de C.V.', '9933772369', 'francocarrera@challenge.com', NULL);

/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;